# tip: slug determines your url: https://kytrinh.me/gathering/<slug>/next
# tip: owner doesn't show up anywhere on the website rn

[[websites]]
name = "kytrinh siteweb"
slug = "kytrinh-siteweb"
about = "website about stuff i've done and things i like"
url = "https://kytrinh.me"
owner = "pink10000"

[[websites]]
name	=	"SheepTester"
slug	=	"sheeptester"
about	=	"personal website with games and little tools written in the HTML programming language"
url	=	"https://sheeptester.github.io/"
atom	=	"https://sheeptester.github.io/longer-tweets/feed.xml"
owner	=	"sean"

[[websites]]
name = "rootydev"
slug = "rootydev"
about = "My personal site/blog. I'll put more stuff there eventually."
url = "https://rooty.dev"
owner = "otisdog8"

[[websites]]
name = "godsped"
slug = "godsped"
about = "the internet garden I tend to"
url = "https://godsped.com/"
atom = "https://godsped.com/feed.xml"
owner = "Samir-Rashid"
[[websites]]
name = "NAME OF WEBSITE"
slug = "sometexthere" # determines your url: https://kytrinh.me/gathering/<slug>/next
about = "WEBSITE DESCRIPTION"
url = "https://URL/"
atom = "" # optional
rss = "" # optional
owner = "YOUR PREFERRED NAME/USERNAME"

